# Generated by Django 3.1.1 on 2020-10-04 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('creator', models.CharField(default='', max_length=100)),
                ('relevant_staff', models.CharField(default='', help_text="separating with ', '", max_length=200)),
                ('time_created', models.DateField(default=django.utils.timezone.now)),
                ('buffer_time', models.DateField(default=django.utils.timezone.now)),
                ('time_to_send', models.DateField(default=django.utils.timezone.now)),
                ('notification_types', models.CharField(default='email, sms, telegram bot, firebase', help_text="separating with ', '", max_length=100)),
                ('repeat', models.IntegerField(default=1)),
                ('interval', models.IntegerField(default=24, help_text='in hour')),
                ('task_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
