# Generated by Django 3.1.2 on 2020-10-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20201012_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
