# Generated by Django 3.1.1 on 2020-09-10 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_created',
            field=models.DateField(default=datetime.datetime(2020, 9, 10, 12, 47, 55, 986916, tzinfo=utc)),
        ),
    ]
