# Generated by Django 3.1.2 on 2020-10-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20201015_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='buffer_time',
            new_name='due_date',
        ),
    ]
