# Generated by Django 3.1.1 on 2020-09-10 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20200910_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
