# Generated by Django 3.1.1 on 2020-09-10 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20200910_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='buffer_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='creator',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_types',
            field=models.CharField(choices=[('E', 'Email'), ('S', 'SMS'), ('T', 'Telegram_Message'), ('F', 'Firebase_Notification')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_to_send',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
